---
- hosts: localhost
  become: yes
  roles:
    - { role: chroot, tags: ["chroot"] }
    - { role: minification, tags: ["minification"] }
    - { role: apt_setup, tags: ["apt_setup"] }
    - { role: gnome, tags: ["gnome"] }
    # - { role: virtualbox, tags: ["virtualbox"] }
    - { role: user_setup, tags: ["user_setup"] }
    - { role: dotfiles, tags: ["dotfiles"] }
    - { role: ros_install, tags: ["ros_install"] }
    - { role: training_install, tags: ["training_install"] }
    - { role: python, tags: ["python"] }
    - { role: vscode, tags: ["vscode"] }
    - { role: containers, tags: ["containers"] }
    - { role: wireguard, tags: ["wireguard"] }
    - { role: apt_clean, tags: ["apt_clean"] }
