- name: Create config dir
  file:
    path: "{{ ros_user_home }}/.config"
    state: directory
    owner: "{{ ros_user }}"
    group: "{{ ros_user }}"
    mode: "0700"

- name: Install isort config
  copy:
    src: isort.cfg
    dest: "{{ ros_user_home }}/.isort.cfg"
    owner: "{{ ros_user }}"
    group: "{{ ros_user }}"

- name: Install pylint config
  copy:
    src: pylintrc
    dest: "{{ ros_user_home }}/.config/pylintrc"
    owner: "{{ ros_user }}"
    group: "{{ ros_user }}"
# TODO add firefox home page
