---
- name: Test for restricted, universe, multiverse
  shell:
    grep '^#deb.*{{ansible_distribution_release}}\(-updates\)\?
    \(restricted\|universe\|multiverse\)' /etc/apt/sources.list
  register: sources_test_result
  ignore_errors: true
  failed_when: false
  changed_when: sources_test_result.rc == 0

- name: Activate restricted, universe, multiverse
  command:
    sed -i".bak-{{ansible_date_time.epoch}}"
    "s/^#\(deb.*{{ansible_distribution_release}}\(-updates\)\?
    \(restricted\|universe\|multiverse\)\)/\1/" /etc/apt/sources.list
  when: sources_test_result.rc == 0

- name: Add an ROS key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

- name: Add ROS repo
  copy:
    dest=/etc/apt/sources.list.d/ros-latest.list content="deb
    http://packages.ros.org/ros/ubuntu {{ansible_distribution_release}} main"
    owner=root group=root mode=644

- name: Update package lists
  apt: update_cache=yes

# ROS Install

- name: Install ROS stuff
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ros-{{ros_release}}-desktop-full
      - python-wstool
      - python-rosinstall
      - python-pip
      - ninja-build
      - ssh
# - name: rosdep init
#   command: rosdep init creates=/etc/ros/rosdep/sources.list.d/20-default.list
