# https://people.canonical.com/~ubuntu-archive/seeds/ubuntu.bionic/desktop.minimal-remove
- name: Minimise desktop
  apt:
    pkg:
    - aisleriot
    - baobab
    - branding-ubuntu
    - cheese
    - cheese-common
    - deja-dup
    - duplicity
    - example-content
    - gir1.2-rb-3.0
    - gir1.2-totem-1.0
    - gir1.2-totemplparser-1.0
    - gnome-calendar
    - gnome-mahjongg
    - gnome-mines
    - gnome-sudoku
    - gnome-todo
    - gnome-todo-common
    - gnome-video-effects
    - guile-2.0-libs
    - hunspell-de-at-frami
    - hunspell-de-ch-frami
    - hunspell-de-de-frami
    - hunspell-en-au
    - hunspell-en-ca
    - hunspell-en-gb
    - hunspell-en-za
    - hunspell-es
    - hunspell-fr
    - hunspell-fr-classical
    - hunspell-it
    - hunspell-pt-br
    - hunspell-pt-pt
    - hunspell-ru
    - hyphen-de
    - hyphen-en-ca
    - hyphen-en-gb
    - hyphen-en-us
    - hyphen-fr
    - hyphen-hr
    - hyphen-it
    - hyphen-pl
    - hyphen-pt-br
    - hyphen-pt-pt
    - hyphen-ru
    - libabw-0.1-1
    - libavahi-ui-gtk3-0
    - libcheese-gtk25
    - libcheese8
    - libdmapsharing-3.0-2
    - libexttextcat-2.0-0
    - libexttextcat-data
    - libfreehand-0.1-1
    - libgnome-games-support-1-3
    - libgnome-games-support-common
    - libgnome-todo
    - libgom-1.0-0
    - libgrilo-0.3-0
    - liblangtag-common
    - liblangtag1
    - libmessaging-menu0
    - libmhash2
    - libminiupnpc10
    - libmwaw-0.3-3
    - libmythes-1.2-0
    - libnatpmp1
    - libneon27-gnutls
    - liborcus-0.13-0
    - libpagemaker-0.0-0
    - libraptor2-0
    - librasqal3
    - librdf0
    - libreoffice-avmedia-backend-gstreamer
    - libreoffice-base-core
    - libreoffice-calc
    - libreoffice-common
    - libreoffice-core
    - libreoffice-draw
    - libreoffice-gnome
    - libreoffice-gtk3
    - libreoffice-help-de
    - libreoffice-help-en-gb
    - libreoffice-help-en-us
    - libreoffice-help-es
    - libreoffice-help-fr
    - libreoffice-help-it
    - libreoffice-help-pt
    - libreoffice-help-pt-br
    - libreoffice-help-ru
    - libreoffice-help-zh-cn
    - libreoffice-help-zh-tw
    - libreoffice-impress
    - libreoffice-l10n-de
    - libreoffice-l10n-en-gb
    - libreoffice-l10n-en-za
    - libreoffice-l10n-es
    - libreoffice-l10n-fr
    - libreoffice-l10n-it
    - libreoffice-l10n-pt
    - libreoffice-l10n-pt-br
    - libreoffice-l10n-ru
    - libreoffice-l10n-zh-cn
    - libreoffice-l10n-zh-tw
    - libreoffice-math
    - libreoffice-ogltrans
    - libreoffice-pdfimport
    - libreoffice-style-breeze
    - libreoffice-style-elementary
    - libreoffice-style-galaxy
    - libreoffice-style-tango
    - libreoffice-writer
    - librevenge-0.0-0
    - librhythmbox-core10
    - libtotem0
    - libvisio-0.1-1
    - libwpd-0.10-10
    - libwpg-0.3-3
    - libwps-0.4-4
    - libyajl2
    - mythes-de
    - mythes-de-ch
    - mythes-en-au
    - mythes-en-us
    - mythes-fr
    - mythes-it
    - mythes-pt-pt
    - mythes-ru
    - python3-uno
    - remmina
    - remmina-common
    - remmina-plugin-rdp
    - remmina-plugin-secret
    - remmina-plugin-vnc
    - rhythmbox
    - rhythmbox-data
    - rhythmbox-plugin-alternative-toolbar
    - rhythmbox-plugins
    - seahorse-daemon
    - shotwell
    - shotwell-common
    - simple-scan
    - thunderbird
    - thunderbird-gnome-support
    - thunderbird-locale-de
    - thunderbird-locale-en
    - thunderbird-locale-en-gb
    - thunderbird-locale-en-us
    - thunderbird-locale-es
    - thunderbird-locale-es-ar
    - thunderbird-locale-es-es
    - thunderbird-locale-fr
    - thunderbird-locale-it
    - thunderbird-locale-pt
    - thunderbird-locale-pt-br
    - thunderbird-locale-pt-pt
    - thunderbird-locale-ru
    - thunderbird-locale-zh-cn
    - thunderbird-locale-zh-hans
    - thunderbird-locale-zh-hant
    - thunderbird-locale-zh-tw
    - totem
    - totem-common
    - totem-plugins
    - transmission-common
    - transmission-gtk
    - ubuntu-web-launchers
    - uno-libs3
    - ure
    - usb-creator-gtk
    - vino
    - zeitgeist-core
    state: absent

- name: Ensure specific packages are not removed by accident
  apt:
    pkg:
    - gnome-control-center
    - gnome-system-monitor
    state: present

- name: Remove live USB user
  user:
    name: ubuntu
    state: absent
    remove: yes
