---
# tasks file for wireguard_role

- name: Install wireguard and other prequisites on the server
  include: 'install_wireguard.yml'
  tags: install_wireguard

- name: Create the configuration directory
  file:
    path: /etc/wireguard
    state: directory
    mode: '0755'

- name: Generate Key Pairs
  shell: wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
  args:
    creates: /etc/wireguard/privatekey
